### ISSUE TITLE
GetNTBuild returns 0 for Windows 10 19044

### ISSUE THREAD

**Issue by deadly-platypus** [jussihi/SMM-Rootkit#1]
After following the build and QEMU run directions, installing Windows 10 from the iso from their website fails.  The only error that gets printed to the console is `ERROR: Failed finding NT build!` and after looking at the code, it appears that `GetNTBuild` is looking for a magic number in a buffer read from memory.  This function seemingly gets called a few times, and then installation halts at different points during the install process.  I have modified the code to print out `val` in `GetNTBuild` if that would be helpful.

**Comment by deadly-platypus** [comment]
Update:  I got the install to complete, but `GetNTBuild` still always seems to return 0, and no further output is displayed.

**Comment by jussihi** [comment]
@deadly-platypus which Windows 10 build are you running?

**Comment by jussihi** [comment]
Also, just making sure, do you get the printouts for before;

```
PML4: ...
NT kernel: ...
PsInitialSystemProcess: ...
InitialSystemProcess: ...
NtVer: ...
```

Could you please paste a log for me of this output?

**Comment by deadly-platypus** [comment]
> @deadly-platypus which Windows 10 build are you running?

Windows 10 Pro, Version 21H2, OS Build 19044.1288



> Also, just making sure, do you get the printouts for before;
> 
> ```
> PML4: ...
> NT kernel: ...
> PsInitialSystemProcess: ...
> InitialSystemProcess: ...
> NtVer: ...
> ```
> 
> Could you please paste a log for me of this output?

```
== Initializing windows context struct ==
  Cleaning up old Windows struct ...
  Dynamic memory allocated before WinCtx init: 24
  PML4: 0x1ad000 Kernel entrypoint: 0x7ffad80cff0
  Trying to find Ntos kernel ... 
  Kernel found!
  NT kernel: 0x7ffadc00000
  Parsing Windows kernel exports ...
  Parsing export table for 64-bit module ...
  Finished Export Table.. NameAmount 3062
  Dynamically allocating table ...
  Filling the export list ...
  Export list successfully filled!
  PsInitialSystemProcess: 0x7ffacf03be0
  SystemProcess: 0x437ba859dfc0
  NtVer: 1000
```

**Comment by jussihi** [comment]
Ah, it seems like Win10 latest kernel is shared with Win11. I will take a look and maybe come up with a patch.

**Comment by jussihi** [comment]
... or if you would like, you can also try to modify the source so that it prints out the buffer allocated in `GetNTBuild` after the `v_memRead` to find a new signature for getting the Build version.

**Comment by deadly-platypus** [comment]
So I did modify the code to print out the buffer, but I am not quite sure what I am looking for.  It appears that you are looking for writes to RCX according the comment in the source.  Is that right?  If so, are writes to RCX really guaranteed to be the instructions we are looking for?  Why not writes to RBX?  Anyway, I looked for RCX writes in the dumped encodings, but I am not sure what form the NT Build number comes in?  I'd be happy to work with you on this =D

**Comment by jussihi** [comment]
You are looking for the build number (if you are printing out `val`). So you should see 19044 there.

Actually, create another variable let's say `UINT32 val2 = *(UINT32 *)(VOID *)b;` (without the bitmask in `val`) and print also that.

**Comment by jussihi** [comment]
Hello @deadly-platypus , 

were you able to get it working?

**Comment by deadly-platypus** [comment]
Sorry, I was busy with other things.  I did what you suggested, and unfortunately, I did not see 19044 in the print outs.  Here's what I got, but I could not find any `4a64` (hex 19044) or `644a` (little endian) in the output.  Am I missing something?

```
5c8948	245c8948
245c89	10245c89
10245c	5710245c
571024	48571024
485710	83485710
834857	ec834857
ec8348	20ec8348
20ec83	3320ec83
3320ec	ff3320ec
ff3320	48ff3320
48ff33	c748ff33
c748ff	41c748ff
41c748	441c748
441c7	a0441c7
a0441	a0441
a04	a04
a	a
0	f000000
f0000	b70f0000
b70f00	5b70f00
5b70f	ed05b70f
ed05b7	63ed05b7
63ed05	5163ed05
5163ed	5163ed
5163	48005163
480051	8b480051
8b4800	d98b4800
d98b48	89d98b48
89d98b	4189d98b
4189d9	c4189d9
c4189	8b0c4189
8b0c41	18b0c41
18b0c	2d018b0c
2d018b	1c2d018b
1c2d01	11c2d01
11c2d	11c2d
11c	11c
1	89000001
890000	7c890000
7c8900	247c8900
247c89	30247c89
30247c	c730247c
c73024	41c73024
41c730	1041c730
1041c7	21041c7
21041	21041
210	210
2	2
0	a9000000
a90000	f7a90000
f7a900	fff7a900
fff7a9	fffff7a9
fffff7	fffffff7
ffffff	75ffffff
75ffff	7175ffff
7175ff	f7175ff
f7175	b60f7175
b60f71	5b60f71
5b60f	1805b60f
1805b6	41805b6
41805	55041805
550418	550418
5504	66005504
660055	89660055
896600	81896600
818966	14818966
148189	1148189
11481	11481
114	114
1	b9000001
b90000	ffb90000
ffb900	ffb900
ffb9	ffb9
ff	ff
0	f000000
f0000	b70f0000
b70f00	5b70f00
5b70f	405b70f
405b7	40405b7
40405	55040405
550404	550404
5504	66005504
660055	23660055
236600	c1236600
c12366	66c12366
66c123	8966c123
8966c1	bb8966c1
bb8966	18bb8966
18bb89	118bb89
118bb	118bb
118	118
1	39000001
390000	3d390000
3d3900	d43d3900
d43d39	3d43d39
3d43d	5503d43d
5503d4	5503d4
5503	66005503
660055	89660055
896600	83896600
838966	16838966
168389	1168389
11683	11683
116	116
1	40000001
400000	88400000
884000	bb884000
bb8840	1abb8840
1abb88	11abb88
11abb	11abb
11a	11a
1	76000001
760000	30760000
307600	48307600
483076	8d483076
8d4830	4c8d4830
4c8d48	244c8d48
244c8d	30244c8d
30244c	e830244c
e83024	72e83024
72e830	4472e830
4472e8	c54472e8
c54472	ffc54472
ffc544	84ffc544
84ffc5	c084ffc5
c084ff	74c084ff
74c084	a74c084
a74c0	8a0a74c0
8a0a74	448a0a74
448a0a	24448a0a
24448a	3024448a
302444	88302444
883024	83883024
838830	1a838830
1a8388	11a8388
11a83	11a83
11a	11a
1	e8000001
e80000	2fe80000
2fe800	2fe800
2fe8	2fe8
2f	2f
0	81000000
810000	3b810000
3b8100	243b8100
243b81	1243b81
1243b	1243b
124	124
1	66000001
660000	89660000
896600	83896600
838966	18838966
188389	1188389
11883	11883
118	118
1	f000001
f0000	840f0000
840f00	58840f00
58840f	e858840f
e85884	12e85884
12e858	12e858
12e8	400012e8
400012	88400012
884000	bb884000
bb8840	1bbb8840
1bbb88	11bbb88
11bbb	11bbb
11b	11b
1	48000001
480000	8b480000
8b4800	5c8b4800
5c8b48	245c8b48
245c8b	38245c8b
38245c	3338245c
333824	c0333824
c03338	48c03338
48c033	8348c033
8348c0	c48348c0
c48348	20c48348
20c483	5f20c483
5f20c4	c35f20c4
c35f20	ccc35f20
ccc35f	ccccc35f
ccccc3	ccccccc3
cccccc	cccccccc
cccccc	cccccccc
cccccc	cccccccc
cccccc	cccccccc
cccccc	cccccccc
cccccc	48cccccc
48cccc	8348cccc
8348cc	ec8348cc
ec8348	28ec8348
28ec83	e828ec83
e828ec	e7e828ec
e7e828	a1e7e828
a1e7e8	b0a1e7e8
b0a1e7	ffb0a1e7
ffb0a1	84ffb0a1
84ffb0	c084ffb0
c084ff	fc084ff
fc084	850fc084
850fc0	41850fc0
41850f	e841850f
e84185	12e84185
12e841	12e841
12e8	a10012e8
a10012	d0a10012
d0a100	2d0a100
2d0a1	2d0a1
2d0	2d0
2	80000002
800000	f7800000
f78000	fff78000
fff780	fffff780
fffff7	48fffff7
48ffff	8348ffff
8348ff	c48348ff
c48348	28c48348
28c483	c328c483
c328c4	ccc328c4
ccc328	ccccc328
ccccc3	ccccccc3
cccccc	cccccccc
cccccc	cccccccc
cccccc	cccccccc
cccccc	cccccccc
cccccc	cccccccc
cccccc	cccccccc
cccccc	48cccccc
48cccc	8b48cccc
8b48cc	c48b48cc
c48b48	4cc48b48
4cc48b	894cc48b
894cc4	48894cc4
48894c	2048894c
204889	44204889
442048	89442048
894420	40894420
408944	18408944

**Comment by jussihi** [comment]
@deadly-platypus 

It seems like the folks at M$ had changed something in RtlGetVersion so that the assembly was changed completely.

before the assembly regarding setting the NtBuild was something in lines:
```
c7 41 0c ef be ad de    mov    DWORD PTR [rcx+0xc],0xdeadbeef
```

Which simply moved a value 0xdeadbeef to rcx + 0xc (0xc, 12, the offset of *build* UINT32 value in [OSVERSIONINFOW](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_osversioninfow)). The fixed value was the build number.

However, this was changed in the recent update to
```
0f b7 05 ef be ad de    movzx  eax,WORD PTR [rip+0xdeadbeef]
```

Now, the build number is no longer behind a fixed value, but it is pointed to a relative offset from current RIP (a pointer). I've added code to handle this situation as well in commit https://github.com/jussihi/SMM-Rootkit/commit/bbb79520cb5d2e92e1f0e98672efa3df7a5b72d3 .

Please check that the patch works and fixes the build number identification issue for you, and I will close this issue.

Merry christmas!

**Comment by jussihi** [comment]
@deadly-platypus , can you please confirm that this indeed fixes the issue for you as well, so that the issue can be closed. Thanks.

**Comment by deadly-platypus** [comment]
The new code finds the build number, thanks!

**Comment by jussihi** [comment]
Thanks and have fun! 

If you modify the code or improve it, please create a PR. I would appreciate it (and the license obligates you to!)

Closing this issue since it was fixed in https://github.com/jussihi/SMM-Rootkit/commit/bbb79520cb5d2e92e1f0e98672efa3df7a5b72d3
